--
-- PostgreSQL database dump
--

\restrict Z3ttpXUgkV9kHOL9OrbmkBWhDh2eZZLipqACeg1kePud9fgIWLa512Wsya6LVTC

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-12-13 00:54:38

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 264 (class 1255 OID 36011)
-- Name: confirm_stock_on_paid(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.confirm_stock_on_paid() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.status IN (2,3) AND OLD.status <> NEW.status THEN
        UPDATE public.product_stock ps
        SET 
            quantity = quantity - oi.quantity,
            reserved = reserved - oi.quantity
        FROM public.order_items oi
        WHERE oi.order_id = NEW.id
          AND oi.product_id = ps.product_id;
    END IF;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.confirm_stock_on_paid() OWNER TO postgres;

--
-- TOC entry 263 (class 1255 OID 36009)
-- Name: deduct_stock_on_order(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.deduct_stock_on_order() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    UPDATE public.product_stock
    SET reserved = reserved + NEW.quantity
    WHERE product_id = NEW.product_id;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.deduct_stock_on_order() OWNER TO postgres;

--
-- TOC entry 265 (class 1255 OID 36014)
-- Name: restore_stock_on_cancel(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.restore_stock_on_cancel() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.status = 4 AND OLD.status <> 4 THEN
        UPDATE public.product_stock ps
        SET reserved = reserved - oi.quantity
        FROM public.order_items oi
        WHERE oi.order_id = NEW.id
          AND oi.product_id = ps.product_id;
    END IF;

    RETURN NEW;
END;
$$;


ALTER FUNCTION public.restore_stock_on_cancel() OWNER TO postgres;

--
-- TOC entry 262 (class 1255 OID 17718)
-- Name: set_updated_at(); Type: FUNCTION; Schema: public; Owner: postgres
--

CREATE FUNCTION public.set_updated_at() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;


ALTER FUNCTION public.set_updated_at() OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 217 (class 1259 OID 17702)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17708)
-- Name: banners; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.banners (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    image character varying(255) NOT NULL,
    link character varying(255),
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.banners OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 17707)
-- Name: banners_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.banners ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.banners_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17817)
-- Name: carts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.carts (
    id bigint NOT NULL,
    user_id bigint,
    cart_item jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.carts OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17816)
-- Name: carts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.carts ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.carts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 17769)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    name character varying(120) NOT NULL,
    slug character varying(150) NOT NULL,
    description text,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT categories_status_chk CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 17768)
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 17876)
-- Name: coupons; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.coupons (
    id bigint NOT NULL,
    product_id bigint,
    code character varying(30) NOT NULL,
    name character varying(150) NOT NULL,
    type smallint NOT NULL,
    value integer NOT NULL,
    start_at timestamp with time zone NOT NULL,
    end_at timestamp with time zone NOT NULL,
    description text,
    total integer DEFAULT 0 NOT NULL,
    used_count integer DEFAULT 0 NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT coupons_counts_chk CHECK (((total >= 0) AND (used_count >= 0))),
    CONSTRAINT coupons_range_chk CHECK ((end_at > start_at)),
    CONSTRAINT coupons_status_chk CHECK ((status = ANY (ARRAY[0, 1]))),
    CONSTRAINT coupons_type_chk CHECK ((type = ANY (ARRAY[1, 2])))
);


ALTER TABLE public.coupons OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17875)
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.coupons ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.coupons_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 36040)
-- Name: drivers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.drivers (
    id bigint NOT NULL,
    user_id bigint,
    full_name character varying(255) NOT NULL,
    phone character varying(20) NOT NULL,
    status character varying(20) DEFAULT 'offline'::character varying,
    rating numeric(3,2) DEFAULT 5.0,
    total_orders integer DEFAULT 0,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.drivers OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 36039)
-- Name: drivers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.drivers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.drivers_id_seq OWNER TO postgres;

--
-- TOC entry 5229 (class 0 OID 0)
-- Dependencies: 254
-- Name: drivers_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.drivers_id_seq OWNED BY public.drivers.id;


--
-- TOC entry 253 (class 1259 OID 36021)
-- Name: inventory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.inventory (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    stock_quantity integer DEFAULT 0 NOT NULL,
    reserved_quantity integer DEFAULT 0 NOT NULL,
    available_quantity integer GENERATED ALWAYS AS ((stock_quantity - reserved_quantity)) STORED,
    low_stock_threshold integer DEFAULT 10 NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.inventory OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 36020)
-- Name: inventory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.inventory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.inventory_id_seq OWNER TO postgres;

--
-- TOC entry 5230 (class 0 OID 0)
-- Dependencies: 252
-- Name: inventory_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.inventory_id_seq OWNED BY public.inventory.id;


--
-- TOC entry 237 (class 1259 OID 17851)
-- Name: order_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_items (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer NOT NULL,
    price integer NOT NULL,
    total integer NOT NULL,
    options jsonb,
    CONSTRAINT order_items_price_chk CHECK ((price >= 0)),
    CONSTRAINT order_items_qty_chk CHECK ((quantity > 0)),
    CONSTRAINT order_items_total_chk CHECK ((total >= 0))
);


ALTER TABLE public.order_items OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17850)
-- Name: order_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_items ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 17864)
-- Name: order_payments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_payments (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    amount integer NOT NULL,
    currency character varying(10) DEFAULT 'VND'::character varying NOT NULL,
    status smallint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    method character varying(30) DEFAULT 'COD'::character varying NOT NULL,
    provider_txn_id character varying(100),
    paid_at timestamp with time zone,
    metadata jsonb,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT order_payments_amount_chk CHECK ((amount >= 0)),
    CONSTRAINT order_payments_status_chk CHECK ((status = ANY (ARRAY[0, 1, 2])))
);


ALTER TABLE public.order_payments OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 17863)
-- Name: order_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_payments ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 36089)
-- Name: order_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_reviews (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    driver_id bigint,
    order_rating smallint NOT NULL,
    driver_rating smallint,
    comment text,
    images text[],
    admin_reply text,
    admin_replied_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT order_reviews_driver_rating_check CHECK (((driver_rating >= 1) AND (driver_rating <= 5))),
    CONSTRAINT order_reviews_order_rating_check CHECK (((order_rating >= 1) AND (order_rating <= 5)))
);


ALTER TABLE public.order_reviews OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 36088)
-- Name: order_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.order_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.order_reviews_id_seq OWNER TO postgres;

--
-- TOC entry 5231 (class 0 OID 0)
-- Dependencies: 258
-- Name: order_reviews_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.order_reviews_id_seq OWNED BY public.order_reviews.id;


--
-- TOC entry 251 (class 1259 OID 35981)
-- Name: order_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_status_history (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    status smallint NOT NULL,
    note character varying(255),
    created_by bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT order_status_history_status_check CHECK ((status = ANY (ARRAY[0, 1, 2, 3, 4])))
);


ALTER TABLE public.order_status_history OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 35980)
-- Name: order_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_status_history ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.order_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 36062)
-- Name: order_status_logs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_status_logs (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    old_status character varying(50),
    new_status character varying(50) NOT NULL,
    notes text,
    changed_by_user_id bigint,
    changed_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.order_status_logs OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 36061)
-- Name: order_status_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.order_status_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.order_status_logs_id_seq OWNER TO postgres;

--
-- TOC entry 5232 (class 0 OID 0)
-- Dependencies: 256
-- Name: order_status_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.order_status_logs_id_seq OWNED BY public.order_status_logs.id;


--
-- TOC entry 235 (class 1259 OID 17827)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    user_id bigint,
    coupons_id bigint,
    ship_name character varying(150) NOT NULL,
    ship_phone character varying(20) NOT NULL,
    ship_address_text character varying(255) NOT NULL,
    price_subtotal integer DEFAULT 0 NOT NULL,
    price_discount integer DEFAULT 0 NOT NULL,
    price_shipping integer DEFAULT 0 NOT NULL,
    total_price integer DEFAULT 0 NOT NULL,
    payment_status smallint DEFAULT 0 NOT NULL,
    status smallint DEFAULT 0 NOT NULL,
    note character varying(255),
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    driver_id bigint,
    driver_accepted_at timestamp with time zone,
    completed_at timestamp with time zone,
    CONSTRAINT orders_nonneg_prices_chk CHECK (((price_subtotal >= 0) AND (price_discount >= 0) AND (price_shipping >= 0) AND (total_price >= 0))),
    CONSTRAINT orders_payment_status_chk CHECK ((payment_status = ANY (ARRAY[0, 1, 2]))),
    CONSTRAINT orders_status_chk CHECK ((status = ANY (ARRAY[0, 1, 2, 3, 4, 5, 6, 7])))
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 5233 (class 0 OID 0)
-- Dependencies: 235
-- Name: COLUMN orders.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.orders.status IS '0=pending, 1=confirmed, 2=driver_assigned, 3=picking_up, 4=delivering, 5=completed, 6=cancelled, 7=refunded';


--
-- TOC entry 234 (class 1259 OID 17826)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 36125)
-- Name: payment_transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment_transactions (
    id bigint NOT NULL,
    order_id bigint NOT NULL,
    payment_id bigint,
    payment_method character varying(50) NOT NULL,
    transaction_id character varying(255),
    amount integer NOT NULL,
    currency character varying(10) DEFAULT 'VND'::character varying,
    status character varying(50) DEFAULT 'pending'::character varying,
    request_data jsonb,
    response_data jsonb,
    callback_data jsonb,
    error_message text,
    paid_at timestamp with time zone,
    refunded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    CONSTRAINT payment_transactions_amount_check CHECK ((amount >= 0))
);


ALTER TABLE public.payment_transactions OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 36124)
-- Name: payment_transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.payment_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.payment_transactions_id_seq OWNER TO postgres;

--
-- TOC entry 5234 (class 0 OID 0)
-- Dependencies: 260
-- Name: payment_transactions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.payment_transactions_id_seq OWNED BY public.payment_transactions.id;


--
-- TOC entry 231 (class 1259 OID 17805)
-- Name: product_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_options (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    name character varying(80) NOT NULL,
    type character varying(50),
    price integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_options_price_chk CHECK ((price >= 0))
);


ALTER TABLE public.product_options OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17804)
-- Name: product_options_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_options ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.product_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17898)
-- Name: product_reviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_reviews (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint NOT NULL,
    rating smallint NOT NULL,
    comment text,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_reviews_rating_chk CHECK (((rating >= 1) AND (rating <= 5))),
    CONSTRAINT product_reviews_status_chk CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.product_reviews OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17897)
-- Name: product_reviews_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_reviews ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.product_reviews_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 35955)
-- Name: product_stock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.product_stock (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    quantity integer DEFAULT 0 NOT NULL,
    reserved integer DEFAULT 0 NOT NULL,
    low_stock_threshold integer DEFAULT 0 NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT product_stock_low_stock_threshold_check CHECK ((low_stock_threshold >= 0)),
    CONSTRAINT product_stock_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT product_stock_reserved_check CHECK ((reserved >= 0)),
    CONSTRAINT product_stock_status_check CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.product_stock OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 35954)
-- Name: product_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.product_stock ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.product_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 17786)
-- Name: products; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.products (
    id bigint NOT NULL,
    category_id bigint NOT NULL,
    name character varying(150) NOT NULL,
    slug character varying(180) NOT NULL,
    images jsonb NOT NULL,
    description text,
    price integer DEFAULT 0 NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT products_price_chk CHECK ((price >= 0)),
    CONSTRAINT products_status_chk CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.products OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17785)
-- Name: products_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.products ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.products_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17917)
-- Name: reports_daily; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.reports_daily (
    id bigint NOT NULL,
    report_date date NOT NULL,
    orders_count integer DEFAULT 0 NOT NULL,
    revenue_total integer DEFAULT 0 NOT NULL,
    customers_count integer DEFAULT 0 NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT reports_daily_nonneg_chk CHECK (((orders_count >= 0) AND (revenue_total >= 0) AND (customers_count >= 0))),
    CONSTRAINT reports_daily_status_chk CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.reports_daily OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17916)
-- Name: reports_daily_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.reports_daily ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.reports_daily_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 35930)
-- Name: shipping_zones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.shipping_zones (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(120) NOT NULL,
    base_fee integer DEFAULT 0 NOT NULL,
    free_minimum integer DEFAULT 0,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT shipping_zones_base_fee_check CHECK ((base_fee >= 0)),
    CONSTRAINT shipping_zones_free_minimum_check CHECK ((free_minimum >= 0)),
    CONSTRAINT shipping_zones_status_check CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.shipping_zones OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 35929)
-- Name: shipping_zones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.shipping_zones ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.shipping_zones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17755)
-- Name: user_addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_addresses (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    name character varying(150) NOT NULL,
    phone character varying(20) NOT NULL,
    address character varying(255) NOT NULL,
    is_default smallint DEFAULT 0 NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    zone_id bigint,
    CONSTRAINT addr_is_default_chk CHECK ((is_default = ANY (ARRAY[0, 1]))),
    CONSTRAINT addr_status_chk CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.user_addresses OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17754)
-- Name: user_addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_addresses ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_addresses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 17738)
-- Name: user_wallets; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_wallets (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider character varying(150) NOT NULL,
    card_holder_name character varying(150),
    card_number character varying(150),
    account_name character varying(150),
    expmonth integer,
    expyear integer,
    cvvhash character varying(255),
    external_customer_id character varying(150),
    external_method_id character varying(150),
    currency character(3) DEFAULT 'VND'::bpchar NOT NULL,
    is_default smallint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT wallets_currency_chk CHECK ((currency ~ '^[A-Z]{3}$'::text)),
    CONSTRAINT wallets_is_default_chk CHECK ((is_default = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.user_wallets OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17737)
-- Name: user_wallets_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.user_wallets ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_wallets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17720)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name character varying(150) NOT NULL,
    email character varying(150) NOT NULL,
    phone character varying(20),
    password character varying(255) NOT NULL,
    avatar character varying(150) NOT NULL,
    role character varying(20) DEFAULT 'user'::character varying NOT NULL,
    status smallint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT users_role_chk CHECK (((role)::text = ANY ((ARRAY['user'::character varying, 'admin'::character varying, 'driver'::character varying])::text[]))),
    CONSTRAINT users_status_chk CHECK ((status = ANY (ARRAY[0, 1])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17719)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4825 (class 2604 OID 36043)
-- Name: drivers id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers ALTER COLUMN id SET DEFAULT nextval('public.drivers_id_seq'::regclass);


--
-- TOC entry 4819 (class 2604 OID 36024)
-- Name: inventory id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory ALTER COLUMN id SET DEFAULT nextval('public.inventory_id_seq'::regclass);


--
-- TOC entry 4833 (class 2604 OID 36092)
-- Name: order_reviews id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_reviews ALTER COLUMN id SET DEFAULT nextval('public.order_reviews_id_seq'::regclass);


--
-- TOC entry 4831 (class 2604 OID 36065)
-- Name: order_status_logs id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_logs ALTER COLUMN id SET DEFAULT nextval('public.order_status_logs_id_seq'::regclass);


--
-- TOC entry 4836 (class 2604 OID 36128)
-- Name: payment_transactions id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_transactions ALTER COLUMN id SET DEFAULT nextval('public.payment_transactions_id_seq'::regclass);


--
-- TOC entry 5179 (class 0 OID 17702)
-- Dependencies: 217
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20251011154131_AddBannerTableFixed	9.0.9
\.


--
-- TOC entry 5181 (class 0 OID 17708)
-- Dependencies: 219
-- Data for Name: banners; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.banners (id, name, image, link, status, created_at, updated_at) FROM stdin;
1	Banner Khuyến mãi Tết 2025	https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=1920&h=600&fit=crop	https://example.com/sale	0	2025-10-01 22:45:24.441791+07	2025-12-11 00:33:07.302688+07
2	Banner Sản phẩm mới	https://images.unsplash.com/photo-1542838132-92c53300491e?w=1920&h=600&fit=crop	https://example.com/new-products	0	2025-10-03 22:45:24.441923+07	2025-12-11 00:34:57.694483+07
3	Banner Free Shipping	https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1920&h=600&fit=crop	https://example.com/free-shipping	0	2025-10-06 22:45:24.441924+07	2025-12-11 00:34:59.981058+07
4	FLASH Food	/assets/images/banner/1765388245649_anhbiafoodmenuwebbannersocialmediabannertemplatefreepsd.jpg	/product/11	1	2025-10-08 22:45:24.441924+07	2025-12-11 00:43:32.316383+07
5	Banner Flash Sale	/assets/images/banner/1765388221285_pngtree-fast-food-fried-chicken-promotion-catering-banner-image584328.jpg	/product/21	1	2025-10-10 22:45:24.441925+07	2025-12-11 00:44:17.495474+07
6	Sale lớn	/assets/images/banner/1765388120770_pngtree-a-delicious-fast-food-arrangement-featuring-cheeseburger-hot-dog-french-fries-png-image20852436.png	/product/10	1	2025-10-14 08:10:09.406813+07	2025-12-11 00:44:48.629749+07
\.


--
-- TOC entry 5195 (class 0 OID 17817)
-- Dependencies: 233
-- Data for Name: carts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.carts (id, user_id, cart_item, created_at) FROM stdin;
\.


--
-- TOC entry 5189 (class 0 OID 17769)
-- Dependencies: 227
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, name, slug, description, status, created_at, updated_at) FROM stdin;
1	Combo bữa ăn	combo-bua-an	Gồm burger + nước + khoai	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
2	Burger	burger	Bánh mì kẹp thịt, phô mai, rau	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
3	Gà rán	ga-ran	Các món gà giòn cay, gà sốt	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
4	Mì & Cơm	mi-com	Các món cơm chiên, mì Ý	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
5	Thức uống	thuc-uong	Nước ngọt, trà sữa, cà phê	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
6	Tráng miệng	trang-mieng	Kem, bánh ngọt, pudding	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
7	Pizza	pizza	Pizza đế mỏng/đế dày, nhiều topping	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
8	Salad & Ăn nhẹ	salad-an-nhe	Salad, khoai, ngô, súp…	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
9	Đồ chay	do-chay	Thực đơn chay thân thiện	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
10	Bữa sáng	bua-sang	Set breakfast, sandwich, cà phê sáng	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
\.


--
-- TOC entry 5203 (class 0 OID 17876)
-- Dependencies: 241
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.coupons (id, product_id, code, name, type, value, start_at, end_at, description, total, used_count, status, created_at, updated_at) FROM stdin;
1	\N	WELCOME10	Giảm 10% đơn đầu	1	10	2025-04-14 23:54:10.536405+07	2026-04-09 23:54:10.536405+07	Áp cho toàn bộ đơn, tối đa 50k	1000	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
2	\N	FREESHIP20K	Giảm 20k phí ship	2	20000	2025-08-12 23:54:10.536405+07	2026-02-08 23:54:10.536405+07	Giảm phí vận chuyển	500	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
3	11	BO10K	Burger bò -10k	2	10000	2025-09-11 23:54:10.536405+07	2026-01-09 23:54:10.536405+07	Giảm trực tiếp 10k cho Burger Bò Phô Mai	300	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
4	22	GA15	Gà cay -15%	1	15	2025-09-26 23:54:10.536405+07	2025-12-10 23:54:10.536405+07	Áp riêng Gà cay Hàn	200	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
5	\N	LUNCH30	Trưa vui -30%	1	30	2025-10-11 11:00:00+07	2026-02-08 23:54:10.536405+07	Khung giờ 11h-14h, tối đa 40k	1000	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
6	\N	DRINK5K	Nước ngọt -5k	2	5000	2025-10-04 23:54:10.536405+07	2026-01-09 23:54:10.536405+07	Áp các đồ uống	800	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
7	33	PASTA7	Mì Ý -7%	1	7	2025-07-13 23:54:10.536405+07	2026-01-09 23:54:10.536405+07	Giảm cho dòng pasta	400	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
8	31	COM5K	Cơm gà -5k	2	5000	2025-09-11 23:54:10.536405+07	2026-02-08 23:54:10.536405+07	Áp riêng cơm gà nước mắm	300	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
9	\N	SWEET15	Tráng miệng -15%	1	15	2025-10-01 23:54:10.536405+07	2026-01-19 23:54:10.536405+07	Áp cho tráng miệng	600	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
10	\N	COMBO20	Combo -20%	1	20	2025-04-14 23:54:10.536405+07	2026-04-09 23:54:10.536405+07	Áp các combo	1000	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
11	45	MILKTEA6K	Trà sữa -6k	2	6000	2025-10-06 23:54:10.536405+07	2025-12-30 23:54:10.536405+07	Áp riêng trà sữa	500	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
12	41	PEPSI3K	Pepsi -3k	2	3000	2025-10-06 23:54:10.536405+07	2025-12-30 23:54:10.536405+07	Áp riêng Pepsi	500	0	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
\.


--
-- TOC entry 5217 (class 0 OID 36040)
-- Dependencies: 255
-- Data for Name: drivers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.drivers (id, user_id, full_name, phone, status, rating, total_orders, created_at, updated_at) FROM stdin;
1	4	Nguyễn Văn Taixe	0901234567	offline	5.00	0	2025-12-13 00:52:41.886407+07	2025-12-13 00:52:41.886407+07
\.


--
-- TOC entry 5215 (class 0 OID 36021)
-- Dependencies: 253
-- Data for Name: inventory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.inventory (id, product_id, stock_quantity, reserved_quantity, low_stock_threshold, updated_at) FROM stdin;
1	1	176	7	10	2025-12-12 23:45:00.494183
2	2	33	0	10	2025-12-12 23:45:00.505131
3	3	105	1	10	2025-12-12 23:45:00.506511
4	4	119	4	10	2025-12-12 23:45:00.507958
5	5	114	8	10	2025-12-12 23:45:00.509361
6	6	199	5	10	2025-12-12 23:45:00.510782
7	7	81	0	10	2025-12-12 23:45:00.512275
8	8	198	9	10	2025-12-12 23:45:00.513128
9	9	61	7	10	2025-12-12 23:45:00.513957
10	10	185	9	10	2025-12-12 23:45:00.514795
11	11	179	9	10	2025-12-12 23:45:00.515601
12	12	192	3	10	2025-12-12 23:45:00.516707
13	13	79	9	10	2025-12-12 23:45:00.51763
14	14	194	7	10	2025-12-12 23:45:00.518443
15	15	164	9	10	2025-12-12 23:45:00.519254
16	16	132	3	10	2025-12-12 23:45:00.52006
17	17	175	6	10	2025-12-12 23:45:00.520856
18	18	72	0	10	2025-12-12 23:45:00.521638
19	19	91	4	10	2025-12-12 23:45:00.522435
20	20	62	4	10	2025-12-12 23:45:00.523217
21	21	46	2	10	2025-12-12 23:45:00.523999
22	22	148	7	10	2025-12-12 23:45:00.524915
23	23	126	3	10	2025-12-12 23:45:00.525694
24	24	194	8	10	2025-12-12 23:45:00.526471
25	25	123	7	10	2025-12-12 23:45:00.527271
26	26	23	0	10	2025-12-12 23:45:00.528046
27	27	45	0	10	2025-12-12 23:45:00.528837
28	28	47	5	10	2025-12-12 23:45:00.529643
29	29	34	0	10	2025-12-12 23:45:00.530442
30	30	53	6	10	2025-12-12 23:45:00.531318
31	31	43	2	10	2025-12-12 23:45:00.532162
32	32	192	3	10	2025-12-12 23:45:00.533043
33	33	135	4	10	2025-12-12 23:45:00.534222
34	34	186	7	10	2025-12-12 23:45:00.535105
35	35	150	9	10	2025-12-12 23:45:00.535939
36	36	26	4	10	2025-12-12 23:45:00.536746
37	37	41	1	10	2025-12-12 23:45:00.537571
38	38	81	2	10	2025-12-12 23:45:00.538371
39	39	177	6	10	2025-12-12 23:45:00.539176
40	40	163	3	10	2025-12-12 23:45:00.540011
41	41	96	0	10	2025-12-12 23:45:00.540887
42	42	172	2	10	2025-12-12 23:45:00.541723
43	43	45	1	10	2025-12-12 23:45:00.542552
44	44	77	9	10	2025-12-12 23:45:00.543376
45	45	162	9	10	2025-12-12 23:45:00.544204
46	46	65	8	10	2025-12-12 23:45:00.54502
47	47	119	7	10	2025-12-12 23:45:00.545859
48	48	99	3	10	2025-12-12 23:45:00.546696
49	49	186	5	10	2025-12-12 23:45:00.547561
50	50	135	1	10	2025-12-12 23:45:00.548349
51	51	124	4	10	2025-12-12 23:45:00.549187
52	52	34	6	10	2025-12-12 23:45:00.55037
53	53	130	1	10	2025-12-12 23:45:00.551221
54	54	77	2	10	2025-12-12 23:45:00.552013
55	55	40	9	10	2025-12-12 23:45:00.5528
56	56	129	9	10	2025-12-12 23:45:00.553617
57	57	168	8	10	2025-12-12 23:45:00.554432
58	58	129	5	10	2025-12-12 23:45:00.555224
59	59	29	1	10	2025-12-12 23:45:00.556002
60	60	171	0	10	2025-12-12 23:45:00.557524
\.


--
-- TOC entry 5199 (class 0 OID 17851)
-- Dependencies: 237
-- Data for Name: order_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_items (id, order_id, product_id, quantity, price, total, options) FROM stdin;
\.


--
-- TOC entry 5201 (class 0 OID 17864)
-- Dependencies: 239
-- Data for Name: order_payments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_payments (id, order_id, amount, currency, status, created_at, method, provider_txn_id, paid_at, metadata, updated_at) FROM stdin;
\.


--
-- TOC entry 5221 (class 0 OID 36089)
-- Dependencies: 259
-- Data for Name: order_reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_reviews (id, order_id, user_id, driver_id, order_rating, driver_rating, comment, images, admin_reply, admin_replied_at, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 5213 (class 0 OID 35981)
-- Dependencies: 251
-- Data for Name: order_status_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_status_history (id, order_id, status, note, created_by, created_at) FROM stdin;
\.


--
-- TOC entry 5219 (class 0 OID 36062)
-- Dependencies: 257
-- Data for Name: order_status_logs; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_status_logs (id, order_id, old_status, new_status, notes, changed_by_user_id, changed_at) FROM stdin;
\.


--
-- TOC entry 5197 (class 0 OID 17827)
-- Dependencies: 235
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, code, user_id, coupons_id, ship_name, ship_phone, ship_address_text, price_subtotal, price_discount, price_shipping, total_price, payment_status, status, note, created_at, updated_at, driver_id, driver_accepted_at, completed_at) FROM stdin;
\.


--
-- TOC entry 5223 (class 0 OID 36125)
-- Dependencies: 261
-- Data for Name: payment_transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment_transactions (id, order_id, payment_id, payment_method, transaction_id, amount, currency, status, request_data, response_data, callback_data, error_message, paid_at, refunded_at, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 5193 (class 0 OID 17805)
-- Dependencies: 231
-- Data for Name: product_options; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_options (id, product_id, name, type, price, created_at, updated_at) FROM stdin;
1	11	Size	Size	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
2	11	Size Vừa	Size	5000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
3	11	Size Lớn	Size	10000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
4	12	Thêm phô mai	Extra	8000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
5	12	Thêm sốt cay	Extra	5000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
6	41	Size Nhỏ	Size	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
7	41	Size Lớn	Size	5000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
8	45	Đường 0%	Sugar	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
9	45	Đường 50%	Sugar	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
10	45	Đường 100%	Sugar	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
11	45	Trân châu thêm	Topping	7000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
12	21	Sốt chấm Tương ớt	Sauce	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
13	21	Sốt Mayonnaise	Sauce	0	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
14	53	Thêm kem vanilla	Extra	10000	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
\.


--
-- TOC entry 5205 (class 0 OID 17898)
-- Dependencies: 243
-- Data for Name: product_reviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_reviews (id, product_id, user_id, rating, comment, status, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 5211 (class 0 OID 35955)
-- Dependencies: 249
-- Data for Name: product_stock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.product_stock (id, product_id, quantity, reserved, low_stock_threshold, status, created_at, updated_at) FROM stdin;
1	1	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
2	2	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
3	3	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
4	4	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
5	5	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
6	6	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
7	7	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
8	8	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
9	9	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
10	10	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
11	11	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
12	12	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
13	13	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
14	14	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
15	15	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
16	16	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
17	17	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
18	18	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
19	19	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
20	20	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
21	21	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
22	22	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
23	23	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
24	24	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
25	25	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
26	26	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
27	27	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
28	28	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
29	29	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
30	30	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
31	31	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
32	32	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
33	33	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
34	34	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
35	35	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
36	36	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
37	37	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
38	38	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
39	39	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
40	40	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
41	41	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
43	43	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
44	44	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
45	45	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
46	46	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
47	47	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
48	48	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
49	49	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
50	50	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
51	51	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
52	52	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
53	53	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
54	54	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
55	55	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
56	56	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
57	57	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
58	58	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
59	59	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
60	60	100	0	0	1	2025-12-12 00:06:57.693224+07	2025-12-12 00:06:57.693224+07
42	42	130	0	20	1	2025-12-12 00:06:57.693224+07	2025-12-12 18:25:57.49807+07
\.


--
-- TOC entry 5191 (class 0 OID 17786)
-- Dependencies: 229
-- Data for Name: products; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.products (id, category_id, name, slug, images, description, price, status, created_at, updated_at) FROM stdin;
1	1	Combo Burger Gà + Pepsi	combo-burger-ga-pepsi	["combo_ga.jpg"]	1 burger gà + Pepsi + khoai tây	79000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
2	1	Combo Burger Bò + Khoai	combo-burger-bo-khoai	["combo_bo.jpg"]	1 burger bò + khoai + nước	89000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
3	1	Combo Gà Rán (2 miếng) + Pepsi	combo-ga-ran-2m-pepsi	["combo_garan.jpg"]	2 miếng gà + Pepsi + khoai	99000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
4	1	Combo Mì Ý Bò + 7Up	combo-mi-y-bo-7up	["combo_mi.jpg"]	Mì Ý sốt bò bằm + 7Up	109000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
5	1	Combo Cơm Gà Nước Mắm	combo-com-ga-nuoc-mam	["combo_comga.jpg"]	Cơm gà chiên nước mắm + nước ngọt	99000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
6	1	Combo Burger Tôm + Khoai	combo-burger-tom-khoai	["combo_tom.jpg"]	Burger tôm + khoai + nước	95000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
7	1	Combo Double Burger Bò	combo-double-burger-bo	["combo_doublebo.jpg"]	Burger bò 2 lớp + khoai + nước	129000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
8	1	Combo Gà Cay Hàn + Khoai	combo-ga-cay-han-khoai	["combo_gacay.jpg"]	Gà cay Hàn + khoai + nước	119000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
9	1	Combo Cánh Gà + Pepsi	combo-canh-ga-pepsi	["combo_canhga.jpg"]	4 cánh gà mật ong + Pepsi	105000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
10	1	Combo Gia Đình 2 Người	combo-gia-dinh-2nguoi	["combo_family2.jpg"]	2 burger + 1 khoai lớn + 2 nước	159000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
11	2	Burger Bò Phô Mai	burger-bo-pho-mai	["burger_bo.jpg"]	Bò + phô mai tan chảy	59000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
12	2	Burger Gà Giòn Cay	burger-ga-gion-cay	["burger_ga.jpg"]	Gà giòn cay, rau xà lách, mayo	56000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
13	2	Burger Tôm	burger-tom	["burger_tom.jpg"]	Tôm chiên giòn + sốt tartar	62000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
14	2	Burger Bò BBQ	burger-bo-bbq	["burger_bbbq.jpg"]	Thịt bò sốt BBQ + hành phi	65000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
15	2	Burger Gà Teriyaki	burger-ga-teriyaki	["burger_gter.jpg"]	Gà sốt Nhật + rau	62000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
16	2	Burger Cá Fillet	burger-ca-fillet	["burger_ca.jpg"]	Cá fillet chiên + sốt tartar	59000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
17	2	Burger Bò Trứng	burger-bo-trung	["burger_botrung.jpg"]	Bò + trứng ốp la + phô mai	64000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
18	2	Burger Nấm Phô Mai	burger-nam-pho-mai	["burger_nam.jpg"]	Nấm xào bơ + phô mai	63000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
19	2	Burger Bò Pepper	burger-bo-pepper	["burger_pepper.jpg"]	Bò sốt tiêu đen	67000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
20	2	Double Cheese Burger	double-cheese-burger	["burger_double.jpg"]	2 lát phô mai + bò	72000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
21	3	Gà Rán Truyền Thống (2 miếng)	ga-ran-truyen-thong-2	["ga_ran_2mieng.jpg"]	Gà rán giòn thơm	69000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
22	3	Gà Cay Hàn Quốc (2 miếng)	ga-cay-han-quoc-2	["ga_cay.jpg"]	Gà sốt cay đậm vị	72000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
23	3	Cánh Gà Sốt Mật Ong (4 cánh)	canh-ga-mat-ong-4	["canh_ga_matong.jpg"]	Cánh gà phủ mật ong	65000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
24	3	Popcorn Chicken	popcorn-chicken	["popcorn_chicken.jpg"]	Gà viên chiên giòn	45000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
25	3	Gà Không Xương Sốt Cay	ga-khong-xuong-sot-cay	["ga_kx_cay.jpg"]	Gà không xương sốt cay	69000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
26	3	Gà Rán Tỏi	ga-ran-toi	["ga_ran_toi.jpg"]	Gà rán vị tỏi	70000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
27	3	Gà Sốt Phô Mai	ga-sot-pho-mai	["ga_phomai.jpg"]	Gà phủ phô mai kéo sợi	78000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
28	3	Cánh Gà Buffalo	canh-ga-buffalo	["ga_buffalo.jpg"]	Cánh gà sốt buffalo cay	71000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
29	3	Đùi Gà Giòn	dui-ga-gion	["ga_duigion.jpg"]	Đùi gà giòn rụm	52000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
30	3	Gà Sốt Chanh Dây	ga-sot-chanh-day	["ga_chanhday.jpg"]	Vị chua ngọt lạ miệng	73000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
31	4	Cơm Gà Chiên Nước Mắm	com-ga-nuoc-mam	["com_ga_nuocmam.jpg"]	Cơm + gà chiên nước mắm	69000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
32	4	Cơm Gà Teriyaki	com-ga-teriyaki	["com_ga_teriyaki.jpg"]	Cơm + gà sốt Nhật	72000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
33	4	Mì Ý Bò Bằm	mi-y-bo-bam	["mi_y_bo_bam.jpg"]	Pasta + sốt bò bằm	75000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
34	4	Mì Ý Sốt Kem Gà	mi-y-sot-kem-ga	["mi_y_kem.jpg"]	Pasta + sốt kem	72000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
35	4	Cơm Chiên Dương Châu	com-chien-duong-chau	["com_duongchau.jpg"]	Cơm chiên thập cẩm	59000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
36	4	Cơm Gà Sốt BBQ	com-ga-sot-bbq	["com_bbq.jpg"]	Cơm + gà sốt BBQ	71000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
37	4	Mì Ý Hải Sản	mi-y-hai-san	["mi_hai_san.jpg"]	Pasta + hải sản	82000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
38	4	Cơm Bò Lúc Lắc	com-bo-luc-lac	["com_luclac.jpg"]	Bò lúc lắc + cơm	89000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
39	4	Cơm Sườn Nướng	com-suon-nuong	["com_suon.jpg"]	Sườn nướng + cơm	86000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
40	4	Cơm Gà Xối Mỡ	com-ga-xoi-mo	["com_xoimo.jpg"]	Gà xối mỡ + cơm	68000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
41	5	Pepsi (500ml)	pepsi-500	["pepsi.jpg"]	Ly 500ml	19000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
42	5	7Up (500ml)	7up-500	["7up.jpg"]	Ly 500ml	19000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
43	5	Trà Đào Cam Sả	tra-dao-cam-sa	["tra_dao.jpg"]	Trà đào tươi, thơm dịu	29000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
44	5	Cà Phê Sữa Đá	ca-phe-sua-da	["cf_suada.jpg"]	Cà phê Việt Nam chuẩn vị	25000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
45	5	Trà Sữa Trân Châu	tra-sua-tran-chau	["trasua_tc.jpg"]	Trà sữa vị truyền thống	32000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
46	5	Nước Chanh Tươi	nuoc-chanh-tuoi	["chanh_tuoi.jpg"]	Chanh tươi giải khát	22000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
47	5	Trà Chanh Sả	tra-chanh-sa	["tra_chanhsa.jpg"]	Trà chanh sả mát	25000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
48	5	Sprite (500ml)	sprite-500	["sprite.jpg"]	Ly 500ml	19000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
49	5	Coca-Cola (500ml)	coca-500	["coca.jpg"]	Ly 500ml	19000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
50	5	Sữa Tươi Trân Châu Đường Đen	sua-tuoi-tcdd	["suatuoi_tcdd.jpg"]	Ngọt đậm đà	35000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
51	6	Kem Ly Vanilla	kem-ly-vanilla	["kem_vanilla.jpg"]	Kem mịn, ngọt dịu	22000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
52	6	Kem Socola	kem-socola	["kem_socola.jpg"]	Vị socola đậm đà	23000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
53	6	Bánh Brownie	banh-brownie	["brownie.jpg"]	Bánh socola mềm ẩm	30000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
54	6	Pudding Trứng	pudding-trung	["pudding.jpg"]	Pudding mềm mịn	27000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
55	6	Bánh Flan Caramel	banh-flan-caramel	["flan.jpg"]	Flan caramel béo mịn	26000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
56	6	Tiramisu Miếng	tiramisu-mieng	["tiramisu.jpg"]	Béo, thơm cà phê	39000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
57	6	Cheesecake Dâu	cheesecake-dau	["cheesecake.jpg"]	Cheesecake vị dâu	42000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
58	6	Bánh Su Kem	banh-su-kem	["sukem.jpg"]	Su kem tươi	28000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
59	6	Kem Dừa Dằm	kem-dua-dam	["kem_dua.jpg"]	Kem dừa & topping	32000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
60	6	Trái Cây Mix Cup	trai-cay-mix-cup	["traicay.jpg"]	Cốc trái cây tươi	35000	1	2025-10-11 23:54:10.536405+07	2025-10-11 23:54:10.536405+07
\.


--
-- TOC entry 5207 (class 0 OID 17917)
-- Dependencies: 245
-- Data for Name: reports_daily; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.reports_daily (id, report_date, orders_count, revenue_total, customers_count, status, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 5209 (class 0 OID 35930)
-- Dependencies: 247
-- Data for Name: shipping_zones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.shipping_zones (id, code, name, base_fee, free_minimum, status, created_at, updated_at) FROM stdin;
1	inner	Nội thành	15000	200000	1	2025-12-11 23:59:31.695237+07	2025-12-12 00:03:43.065073+07
2	outer	Ngoại thành	30000	300000	1	2025-12-11 23:59:31.695237+07	2025-12-12 00:03:43.065073+07
\.


--
-- TOC entry 5187 (class 0 OID 17755)
-- Dependencies: 225
-- Data for Name: user_addresses; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_addresses (id, user_id, name, phone, address, is_default, status, created_at, updated_at, zone_id) FROM stdin;
\.


--
-- TOC entry 5185 (class 0 OID 17738)
-- Dependencies: 223
-- Data for Name: user_wallets; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_wallets (id, user_id, provider, card_holder_name, card_number, account_name, expmonth, expyear, cvvhash, external_customer_id, external_method_id, currency, is_default, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 5183 (class 0 OID 17720)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, phone, password, avatar, role, status, created_at, updated_at) FROM stdin;
1	Mỹ Linh	Linhbuithimy14@gmail.com	0987654322	$2a$12$2MzbrUGIYTCbupY0ZI0.LOAV.X3F6rIKBpcJ.O8bo5gMa18qLyjmu	default.png	admin	1	2025-11-06 15:41:22.252877+07	2025-12-12 18:25:02.760546+07
4	Nguyễn Văn Taixe	drivera@yumfast.com	0901234567	$2a$12$HASH_PASSWORD	driver_a.jpg	driver	1	2025-12-13 00:52:41.886407+07	2025-12-13 00:52:41.886407+07
\.


--
-- TOC entry 5235 (class 0 OID 0)
-- Dependencies: 218
-- Name: banners_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.banners_id_seq', 6, true);


--
-- TOC entry 5236 (class 0 OID 0)
-- Dependencies: 232
-- Name: carts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.carts_id_seq', 1, false);


--
-- TOC entry 5237 (class 0 OID 0)
-- Dependencies: 226
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 10, true);


--
-- TOC entry 5238 (class 0 OID 0)
-- Dependencies: 240
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.coupons_id_seq', 12, true);


--
-- TOC entry 5239 (class 0 OID 0)
-- Dependencies: 254
-- Name: drivers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.drivers_id_seq', 1, true);


--
-- TOC entry 5240 (class 0 OID 0)
-- Dependencies: 252
-- Name: inventory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.inventory_id_seq', 60, true);


--
-- TOC entry 5241 (class 0 OID 0)
-- Dependencies: 236
-- Name: order_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_items_id_seq', 1, false);


--
-- TOC entry 5242 (class 0 OID 0)
-- Dependencies: 238
-- Name: order_payments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_payments_id_seq', 1, false);


--
-- TOC entry 5243 (class 0 OID 0)
-- Dependencies: 258
-- Name: order_reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_reviews_id_seq', 1, false);


--
-- TOC entry 5244 (class 0 OID 0)
-- Dependencies: 250
-- Name: order_status_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_status_history_id_seq', 1, false);


--
-- TOC entry 5245 (class 0 OID 0)
-- Dependencies: 256
-- Name: order_status_logs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_status_logs_id_seq', 1, false);


--
-- TOC entry 5246 (class 0 OID 0)
-- Dependencies: 234
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 1, false);


--
-- TOC entry 5247 (class 0 OID 0)
-- Dependencies: 260
-- Name: payment_transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_transactions_id_seq', 1, false);


--
-- TOC entry 5248 (class 0 OID 0)
-- Dependencies: 230
-- Name: product_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_options_id_seq', 14, true);


--
-- TOC entry 5249 (class 0 OID 0)
-- Dependencies: 242
-- Name: product_reviews_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_reviews_id_seq', 1, false);


--
-- TOC entry 5250 (class 0 OID 0)
-- Dependencies: 248
-- Name: product_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.product_stock_id_seq', 62, true);


--
-- TOC entry 5251 (class 0 OID 0)
-- Dependencies: 228
-- Name: products_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.products_id_seq', 60, true);


--
-- TOC entry 5252 (class 0 OID 0)
-- Dependencies: 244
-- Name: reports_daily_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.reports_daily_id_seq', 1, false);


--
-- TOC entry 5253 (class 0 OID 0)
-- Dependencies: 246
-- Name: shipping_zones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.shipping_zones_id_seq', 4, true);


--
-- TOC entry 5254 (class 0 OID 0)
-- Dependencies: 224
-- Name: user_addresses_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_addresses_id_seq', 1, false);


--
-- TOC entry 5255 (class 0 OID 0)
-- Dependencies: 222
-- Name: user_wallets_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_wallets_id_seq', 1, false);


--
-- TOC entry 5256 (class 0 OID 0)
-- Dependencies: 220
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 4, true);


--
-- TOC entry 4879 (class 2606 OID 17706)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 4881 (class 2606 OID 17717)
-- Name: banners PK_banners; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.banners
    ADD CONSTRAINT "PK_banners" PRIMARY KEY (id);


--
-- TOC entry 4912 (class 2606 OID 17824)
-- Name: carts carts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT carts_pkey PRIMARY KEY (id);


--
-- TOC entry 4897 (class 2606 OID 17781)
-- Name: categories categories_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_name_key UNIQUE (name);


--
-- TOC entry 4899 (class 2606 OID 17779)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4901 (class 2606 OID 17783)
-- Name: categories categories_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_slug_key UNIQUE (slug);


--
-- TOC entry 4930 (class 2606 OID 17893)
-- Name: coupons coupons_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_code_key UNIQUE (code);


--
-- TOC entry 4932 (class 2606 OID 17891)
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- TOC entry 4963 (class 2606 OID 36050)
-- Name: drivers drivers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_pkey PRIMARY KEY (id);


--
-- TOC entry 4965 (class 2606 OID 36052)
-- Name: drivers drivers_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_user_id_key UNIQUE (user_id);


--
-- TOC entry 4959 (class 2606 OID 36031)
-- Name: inventory inventory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_pkey PRIMARY KEY (id);


--
-- TOC entry 4961 (class 2606 OID 36033)
-- Name: inventory inventory_product_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_product_id_key UNIQUE (product_id);


--
-- TOC entry 4924 (class 2606 OID 17860)
-- Name: order_items order_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT order_items_pkey PRIMARY KEY (id);


--
-- TOC entry 4927 (class 2606 OID 17873)
-- Name: order_payments order_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_payments
    ADD CONSTRAINT order_payments_pkey PRIMARY KEY (id);


--
-- TOC entry 4976 (class 2606 OID 36102)
-- Name: order_reviews order_reviews_order_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_reviews
    ADD CONSTRAINT order_reviews_order_id_key UNIQUE (order_id);


--
-- TOC entry 4978 (class 2606 OID 36100)
-- Name: order_reviews order_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_reviews
    ADD CONSTRAINT order_reviews_pkey PRIMARY KEY (id);


--
-- TOC entry 4957 (class 2606 OID 35987)
-- Name: order_status_history order_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT order_status_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4970 (class 2606 OID 36070)
-- Name: order_status_logs order_status_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_logs
    ADD CONSTRAINT order_status_logs_pkey PRIMARY KEY (id);


--
-- TOC entry 4918 (class 2606 OID 17846)
-- Name: orders orders_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_code_key UNIQUE (code);


--
-- TOC entry 4920 (class 2606 OID 17844)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4984 (class 2606 OID 36137)
-- Name: payment_transactions payment_transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4986 (class 2606 OID 36139)
-- Name: payment_transactions payment_transactions_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_transaction_id_key UNIQUE (transaction_id);


--
-- TOC entry 4910 (class 2606 OID 17813)
-- Name: product_options product_options_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_options
    ADD CONSTRAINT product_options_pkey PRIMARY KEY (id);


--
-- TOC entry 4938 (class 2606 OID 17909)
-- Name: product_reviews product_reviews_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT product_reviews_pkey PRIMARY KEY (id);


--
-- TOC entry 4951 (class 2606 OID 35969)
-- Name: product_stock product_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_stock
    ADD CONSTRAINT product_stock_pkey PRIMARY KEY (id);


--
-- TOC entry 4953 (class 2606 OID 35971)
-- Name: product_stock product_stock_product_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_stock
    ADD CONSTRAINT product_stock_product_id_key UNIQUE (product_id);


--
-- TOC entry 4905 (class 2606 OID 17798)
-- Name: products products_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_pkey PRIMARY KEY (id);


--
-- TOC entry 4907 (class 2606 OID 17800)
-- Name: products products_slug_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT products_slug_key UNIQUE (slug);


--
-- TOC entry 4941 (class 2606 OID 17929)
-- Name: reports_daily reports_daily_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_daily
    ADD CONSTRAINT reports_daily_pkey PRIMARY KEY (id);


--
-- TOC entry 4943 (class 2606 OID 17931)
-- Name: reports_daily reports_daily_report_date_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.reports_daily
    ADD CONSTRAINT reports_daily_report_date_key UNIQUE (report_date);


--
-- TOC entry 4946 (class 2606 OID 35944)
-- Name: shipping_zones shipping_zones_code_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipping_zones
    ADD CONSTRAINT shipping_zones_code_key UNIQUE (code);


--
-- TOC entry 4948 (class 2606 OID 35942)
-- Name: shipping_zones shipping_zones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.shipping_zones
    ADD CONSTRAINT shipping_zones_pkey PRIMARY KEY (id);


--
-- TOC entry 4895 (class 2606 OID 17765)
-- Name: user_addresses user_addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT user_addresses_pkey PRIMARY KEY (id);


--
-- TOC entry 4891 (class 2606 OID 17750)
-- Name: user_wallets user_wallets_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_wallets
    ADD CONSTRAINT user_wallets_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 17734)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4887 (class 2606 OID 17732)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4882 (class 1259 OID 17914)
-- Name: idx_banners_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_banners_status ON public.banners USING btree (status);


--
-- TOC entry 4913 (class 1259 OID 17825)
-- Name: idx_carts_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_carts_user ON public.carts USING btree (user_id);


--
-- TOC entry 4933 (class 1259 OID 17894)
-- Name: idx_coupons_product; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_coupons_product ON public.coupons USING btree (product_id);


--
-- TOC entry 4934 (class 1259 OID 17895)
-- Name: idx_coupons_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_coupons_status ON public.coupons USING btree (status);


--
-- TOC entry 4966 (class 1259 OID 36059)
-- Name: idx_drivers_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drivers_status ON public.drivers USING btree (status);


--
-- TOC entry 4967 (class 1259 OID 36058)
-- Name: idx_drivers_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_drivers_user_id ON public.drivers USING btree (user_id);


--
-- TOC entry 4921 (class 1259 OID 17861)
-- Name: idx_order_items_order; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_items_order ON public.order_items USING btree (order_id);


--
-- TOC entry 4922 (class 1259 OID 17862)
-- Name: idx_order_items_prod; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_items_prod ON public.order_items USING btree (product_id);


--
-- TOC entry 4925 (class 1259 OID 17874)
-- Name: idx_order_payments_order; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_payments_order ON public.order_payments USING btree (order_id);


--
-- TOC entry 4971 (class 1259 OID 36121)
-- Name: idx_order_reviews_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_reviews_created_at ON public.order_reviews USING btree (created_at DESC);


--
-- TOC entry 4972 (class 1259 OID 36120)
-- Name: idx_order_reviews_driver_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_reviews_driver_id ON public.order_reviews USING btree (driver_id);


--
-- TOC entry 4973 (class 1259 OID 36118)
-- Name: idx_order_reviews_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_reviews_order_id ON public.order_reviews USING btree (order_id);


--
-- TOC entry 4974 (class 1259 OID 36119)
-- Name: idx_order_reviews_user_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_reviews_user_id ON public.order_reviews USING btree (user_id);


--
-- TOC entry 4954 (class 1259 OID 35998)
-- Name: idx_order_status_history_order; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_status_history_order ON public.order_status_history USING btree (order_id);


--
-- TOC entry 4955 (class 1259 OID 35999)
-- Name: idx_order_status_history_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_status_history_status ON public.order_status_history USING btree (status);


--
-- TOC entry 4968 (class 1259 OID 36081)
-- Name: idx_order_status_logs_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_order_status_logs_order_id ON public.order_status_logs USING btree (order_id);


--
-- TOC entry 4914 (class 1259 OID 36087)
-- Name: idx_orders_driver_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orders_driver_id ON public.orders USING btree (driver_id);


--
-- TOC entry 4915 (class 1259 OID 17848)
-- Name: idx_orders_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orders_status ON public.orders USING btree (status);


--
-- TOC entry 4916 (class 1259 OID 17847)
-- Name: idx_orders_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_orders_user ON public.orders USING btree (user_id);


--
-- TOC entry 4979 (class 1259 OID 36150)
-- Name: idx_payment_transactions_order_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_transactions_order_id ON public.payment_transactions USING btree (order_id);


--
-- TOC entry 4980 (class 1259 OID 36151)
-- Name: idx_payment_transactions_payment_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_transactions_payment_id ON public.payment_transactions USING btree (payment_id);


--
-- TOC entry 4981 (class 1259 OID 36153)
-- Name: idx_payment_transactions_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_transactions_status ON public.payment_transactions USING btree (status);


--
-- TOC entry 4982 (class 1259 OID 36152)
-- Name: idx_payment_transactions_transaction_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_payment_transactions_transaction_id ON public.payment_transactions USING btree (transaction_id);


--
-- TOC entry 4908 (class 1259 OID 17814)
-- Name: idx_product_options_product; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_options_product ON public.product_options USING btree (product_id);


--
-- TOC entry 4949 (class 1259 OID 35977)
-- Name: idx_product_stock_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_product_stock_status ON public.product_stock USING btree (status);


--
-- TOC entry 4902 (class 1259 OID 17801)
-- Name: idx_products_category; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_category ON public.products USING btree (category_id);


--
-- TOC entry 4903 (class 1259 OID 17802)
-- Name: idx_products_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_products_status ON public.products USING btree (status);


--
-- TOC entry 4935 (class 1259 OID 17911)
-- Name: idx_reviews_product; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_reviews_product ON public.product_reviews USING btree (product_id);


--
-- TOC entry 4936 (class 1259 OID 17912)
-- Name: idx_reviews_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_reviews_user ON public.product_reviews USING btree (user_id);


--
-- TOC entry 4944 (class 1259 OID 35945)
-- Name: idx_shipping_zones_status; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_shipping_zones_status ON public.shipping_zones USING btree (status);


--
-- TOC entry 4892 (class 1259 OID 17766)
-- Name: idx_user_addresses_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_addresses_user ON public.user_addresses USING btree (user_id);


--
-- TOC entry 4893 (class 1259 OID 35952)
-- Name: idx_user_addresses_zone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_addresses_zone ON public.user_addresses USING btree (zone_id);


--
-- TOC entry 4888 (class 1259 OID 17752)
-- Name: idx_user_wallets_provider; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_wallets_provider ON public.user_wallets USING btree (provider);


--
-- TOC entry 4889 (class 1259 OID 17751)
-- Name: idx_user_wallets_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_user_wallets_user ON public.user_wallets USING btree (user_id);


--
-- TOC entry 4883 (class 1259 OID 17735)
-- Name: idx_users_phone; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_users_phone ON public.users USING btree (phone);


--
-- TOC entry 4928 (class 1259 OID 36004)
-- Name: ux_order_payments_provider_txn; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_order_payments_provider_txn ON public.order_payments USING btree (provider_txn_id) WHERE (provider_txn_id IS NOT NULL);


--
-- TOC entry 4939 (class 1259 OID 17910)
-- Name: ux_reviews_product_user; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX ux_reviews_product_user ON public.product_reviews USING btree (product_id, user_id);


--
-- TOC entry 5014 (class 2620 OID 17915)
-- Name: banners trg_banners_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_banners_updated_at BEFORE UPDATE ON public.banners FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5018 (class 2620 OID 17784)
-- Name: categories trg_categories_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_categories_updated_at BEFORE UPDATE ON public.categories FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5026 (class 2620 OID 17896)
-- Name: coupons trg_coupons_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_coupons_updated_at BEFORE UPDATE ON public.coupons FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5031 (class 2620 OID 36060)
-- Name: drivers trg_drivers_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_drivers_updated_at BEFORE UPDATE ON public.drivers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5021 (class 2620 OID 36016)
-- Name: orders trg_order_cancel_restore_stock; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_order_cancel_restore_stock AFTER UPDATE OF status ON public.orders FOR EACH ROW EXECUTE FUNCTION public.restore_stock_on_cancel();


--
-- TOC entry 5024 (class 2620 OID 36010)
-- Name: order_items trg_order_items_reserve_stock; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_order_items_reserve_stock AFTER INSERT ON public.order_items FOR EACH ROW EXECUTE FUNCTION public.deduct_stock_on_order();


--
-- TOC entry 5022 (class 2620 OID 36013)
-- Name: orders trg_order_paid_deduct_stock; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_order_paid_deduct_stock AFTER UPDATE OF status ON public.orders FOR EACH ROW EXECUTE FUNCTION public.confirm_stock_on_paid();


--
-- TOC entry 5025 (class 2620 OID 36008)
-- Name: order_payments trg_order_payments_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_order_payments_updated_at BEFORE UPDATE ON public.order_payments FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5032 (class 2620 OID 36122)
-- Name: order_reviews trg_order_reviews_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_order_reviews_updated_at BEFORE UPDATE ON public.order_reviews FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5023 (class 2620 OID 17849)
-- Name: orders trg_orders_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_orders_updated_at BEFORE UPDATE ON public.orders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5033 (class 2620 OID 36154)
-- Name: payment_transactions trg_payment_transactions_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_payment_transactions_updated_at BEFORE UPDATE ON public.payment_transactions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5020 (class 2620 OID 17815)
-- Name: product_options trg_product_options_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_product_options_updated_at BEFORE UPDATE ON public.product_options FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5027 (class 2620 OID 17913)
-- Name: product_reviews trg_product_reviews_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_product_reviews_updated_at BEFORE UPDATE ON public.product_reviews FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5030 (class 2620 OID 35979)
-- Name: product_stock trg_product_stock_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_product_stock_updated_at BEFORE UPDATE ON public.product_stock FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5019 (class 2620 OID 17803)
-- Name: products trg_products_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5028 (class 2620 OID 17932)
-- Name: reports_daily trg_reports_daily_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_reports_daily_updated_at BEFORE UPDATE ON public.reports_daily FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5029 (class 2620 OID 35953)
-- Name: shipping_zones trg_shipping_zones_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_shipping_zones_updated_at BEFORE UPDATE ON public.shipping_zones FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5017 (class 2620 OID 17767)
-- Name: user_addresses trg_user_addresses_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_user_addresses_updated_at BEFORE UPDATE ON public.user_addresses FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5016 (class 2620 OID 17753)
-- Name: user_wallets trg_user_wallets_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_user_wallets_updated_at BEFORE UPDATE ON public.user_wallets FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5015 (class 2620 OID 17736)
-- Name: users trg_users_updated_at; Type: TRIGGER; Schema: public; Owner: postgres
--

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


--
-- TOC entry 5006 (class 2606 OID 36053)
-- Name: drivers drivers_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.drivers
    ADD CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4992 (class 2606 OID 17953)
-- Name: carts fk_carts_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.carts
    ADD CONSTRAINT fk_carts_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4999 (class 2606 OID 17963)
-- Name: coupons fk_coupons_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT fk_coupons_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE SET NULL;


--
-- TOC entry 4996 (class 2606 OID 17973)
-- Name: order_items fk_order_items_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- TOC entry 4997 (class 2606 OID 17978)
-- Name: order_items fk_order_items_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_items
    ADD CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE RESTRICT;


--
-- TOC entry 4998 (class 2606 OID 17983)
-- Name: order_payments fk_order_payments_order; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_payments
    ADD CONSTRAINT fk_order_payments_order FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- TOC entry 4993 (class 2606 OID 17968)
-- Name: orders fk_orders_coupon; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_coupon FOREIGN KEY (coupons_id) REFERENCES public.coupons(id) ON DELETE SET NULL;


--
-- TOC entry 4994 (class 2606 OID 17958)
-- Name: orders fk_orders_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 4991 (class 2606 OID 17948)
-- Name: product_options fk_product_options_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_options
    ADD CONSTRAINT fk_product_options_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- TOC entry 4990 (class 2606 OID 17943)
-- Name: products fk_products_category; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.products
    ADD CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES public.categories(id) ON DELETE RESTRICT;


--
-- TOC entry 5000 (class 2606 OID 17988)
-- Name: product_reviews fk_reviews_product; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT fk_reviews_product FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- TOC entry 5001 (class 2606 OID 17993)
-- Name: product_reviews fk_reviews_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_reviews
    ADD CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4988 (class 2606 OID 17938)
-- Name: user_addresses fk_user_addresses_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 4989 (class 2606 OID 35947)
-- Name: user_addresses fk_user_addresses_zone; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_addresses
    ADD CONSTRAINT fk_user_addresses_zone FOREIGN KEY (zone_id) REFERENCES public.shipping_zones(id) ON DELETE SET NULL;


--
-- TOC entry 4987 (class 2606 OID 17933)
-- Name: user_wallets fk_user_wallets_user; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_wallets
    ADD CONSTRAINT fk_user_wallets_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5005 (class 2606 OID 36034)
-- Name: inventory inventory_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.inventory
    ADD CONSTRAINT inventory_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


--
-- TOC entry 5009 (class 2606 OID 36113)
-- Name: order_reviews order_reviews_driver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_reviews
    ADD CONSTRAINT order_reviews_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5010 (class 2606 OID 36103)
-- Name: order_reviews order_reviews_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_reviews
    ADD CONSTRAINT order_reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- TOC entry 5011 (class 2606 OID 36108)
-- Name: order_reviews order_reviews_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_reviews
    ADD CONSTRAINT order_reviews_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- TOC entry 5003 (class 2606 OID 35993)
-- Name: order_status_history order_status_history_created_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT order_status_history_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5004 (class 2606 OID 35988)
-- Name: order_status_history order_status_history_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_history
    ADD CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- TOC entry 5007 (class 2606 OID 36076)
-- Name: order_status_logs order_status_logs_changed_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_logs
    ADD CONSTRAINT order_status_logs_changed_by_user_id_fkey FOREIGN KEY (changed_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- TOC entry 5008 (class 2606 OID 36071)
-- Name: order_status_logs order_status_logs_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_status_logs
    ADD CONSTRAINT order_status_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- TOC entry 4995 (class 2606 OID 36082)
-- Name: orders orders_driver_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id) ON DELETE SET NULL;


--
-- TOC entry 5012 (class 2606 OID 36140)
-- Name: payment_transactions payment_transactions_order_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id) ON DELETE CASCADE;


--
-- TOC entry 5013 (class 2606 OID 36145)
-- Name: payment_transactions payment_transactions_payment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment_transactions
    ADD CONSTRAINT payment_transactions_payment_id_fkey FOREIGN KEY (payment_id) REFERENCES public.order_payments(id) ON DELETE SET NULL;


--
-- TOC entry 5002 (class 2606 OID 35972)
-- Name: product_stock product_stock_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.product_stock
    ADD CONSTRAINT product_stock_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


-- Completed on 2025-12-13 00:54:38

--
-- PostgreSQL database dump complete
--

\unrestrict Z3ttpXUgkV9kHOL9OrbmkBWhDh2eZZLipqACeg1kePud9fgIWLa512Wsya6LVTC

